import Image from "next/image";
import Link from "next/link";
import { useFetchArray } from "src/hooks/useFetchArray";
import styles from "src/components/Category/Category.module.css";
import formatDate from "libs/utils";
import Head from "next/head";

export const SubCategoryListItem = () => {
  const { data, error, isLoading, isEmpty } = useFetchArray(`subcategory`);

  if (isLoading) {
    return <div>Loading...</div>;
  }
  if (error) {
    return <div>Error</div>;
  }
  if (isEmpty) {
    return <div>There is no article.</div>;
  }
  return (
    <>
      <Head>
        <title>Onesite - {data.contents[0].subcategory[0].name}記事一覧</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="w-11/12 max-w-3xl mx-auto mt-8">
        <section>
          <h1 className={`font-bold tracking-wide text-center ${styles.title}`}>
            {data.contents[0].subcategory[0].name}
          </h1>
          <nav>
            <ol className="flex  justify-center text-sky-500">
              <li>
                <Link href={`/`} prefetch={false}>
                  <a>
                    Home<span className="mx-2 text-stone-900">/</span>
                  </a>
                </Link>
              </li>
              <li>{data.contents[0].subcategory[0].name}</li>
            </ol>
          </nav>
          <div className="grid grid-cols-3 gap-4 mt-4">
            {data.contents.map((content) => (
              <article
                key={content.id}
                className={`text-center bg-gradient-to-tr from-post-bg-t to-post-bg-b pt-8 pb-7 px-7 rounded-3xl ${styles.categoryPost}`}
              >
                <Link href={`/blogs/${content.id}`} prefetch={false}>
                  <a>
                    <Image
                      src={content.icon.url}
                      alt={content.alt}
                      width={70}
                      height={70}
                      className="rounded-xl"
                    />
                  </a>
                </Link>
                <Link href={`/categories/${content.category.id}`}>
                  <a>
                    <p
                      className={`font-medium mt-2 text-sky-600 ${styles.category}`}
                    >
                      {content.category.name}
                    </p>
                  </a>
                </Link>
                <Link href={`/blogs/${content.id}`} prefetch={false}>
                  <a>
                    <h2 className={`font-bold mt-2 mb-3 ${styles.postTitle}`}>
                      {content.title}
                    </h2>
                  </a>
                </Link>
                <div className="flex justify-center items-center">
                  <Image
                    src={content.subcategory[0].icon.url}
                    alt={content.subcategory[0].icon.url}
                    width={32}
                    height={32}
                  />
                  <p className="ml-1 text-sm font-bold mr-4">{content.subcategory[0].name}</p>
                </div>
              </article>
            ))}
          </div>
        </section>
      </div>
    </>
  );
};
