import Image from "next/image";
import Link from "next/link";
import { formatDate } from "libs/utils";
import { useFetchArray } from "src/hooks/useFetchArray";
import Head from "next/head";
import styles from "src/components/Category/Category.module.css";

export const CategoryItems = () => {
  const { data, error, isLoading, isEmpty } = useFetchArray(`blogs`);

  if (isLoading) {
    return <div>Loading....</div>;
  }
  if (error) {
    return <div>error</div>;
  }
  if (isEmpty) {
    return <div>ブログ記事はありません</div>;
  }
  return (
    <>
      <Head>
        <title>Onesite - {data.contents[0].category.name}記事一覧</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <div className="pt-28">
          <h1 className={`font-bold tracking-wide ${styles.title}`}>
            {data.contents[0].category.name}
          </h1>
          <div className="grid grid-cols-3 gap-6 mt-9">
            {data.contents.map((blog) => (
              <article key={blog.id}>
                <Link href={`/blogs/${blog.id}`} prefetch={false}>
                  <a>
                    <Image
                      src={blog.eyecatch.url}
                      alt={blog.alt}
                      width={blog.eyecatch.width}
                      height={blog.eyecatch.height}
                      className="rounded-xl"
                    />
                    <p>{blog.category.name}</p>
                    <h2>{blog.title}</h2>
                  </a>
                </Link>
                <div>
                  <div>
                    <Image
                      src={blog.subcategory.icon.url}
                      alt={blog.subcategory.icon.alt}
                      width={blog.subcategory.icon.width}
                      height={blog.subcategory.icon.height}
                    />
                    <p>{blog.subcategory.name}</p>
                  </div>
                  <p>
                    <Image src="/clock.svg" alt="日時" width={22} height={22} />
                    <time>{formatDate(blog.updatedAt)}</time>
                  </p>
                </div>
              </article>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};
