import { client } from "libs/client";
import Head from "next/head";
import { CategoryItems } from "src/components/Category/CategoryItems";
import { SWRConfig } from "swr";

// 静的生成のためのパスを指定します
export const getStaticPaths = async () => {
  const data = await client.get({ endpoint: "categories" });
  const paths = data.contents.map((content) => `/categories/${content.id}`);
  return { paths, fallback: "blocking" };
};

// データをテンプレートに受け渡す部分の処理を記述します
export const getStaticProps = async (context) => {
  const id = context.params.id;
  const data = await client.get({
    endpoint: "blogs",
    queries: { filters: `category[equals]${id}` },
  });
  return {
    props: {
      fallback: {
        "https://ippei-shimizu.microcms.io/api/v1/blogs": data,
      },
    },
    revalidate: 10,
  };
};

export const CategoryList = (props) => {
  const { fallback } = props;
  return (
    <>
      <Head>
        <title>- Onesite フロントエンドの技術アウトプットブログ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SWRConfig value={{ fallback }}>
        <CategoryItems />
      </SWRConfig>
    </>
  );
};

export default CategoryList;
