import { client } from "libs/client";
import Head from "next/head";
import Link from "next/link";
import { Suspense } from "react";
import { HomeFv } from "src/components/Home/HomeFv";
import { LatestPost } from "src/components/Home/LatestPost";
import { SubCategoryItem } from "src/components/SubCategory/SubCategoryItem";
import { API_URL_M_CMS, PostListLimit } from "src/utils/const";
import { SWRConfig } from "swr";

export const getStaticProps = async () => {
  const blogData = await client.get({
    endpoint: "blogs",
    queries: { limit: PostListLimit },
  });
  const subCategoryData = await client.get({ endpoint: "subcategory" });
  const API_BLOG = `${API_URL_M_CMS}/blogs`;
  return {
    props: {
      fallback: {
        [API_BLOG]: blogData,
      },
      subCategory: subCategoryData.contents,
    },
    revalidate: 10,
  };
};

const Home = (props) => {
  const { fallback } = props;
  return (
    <>
      <Head>
        <title>Onesite - フロントエンドの技術アウトプットブログ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <SWRConfig value={{ fallback }}>
          <HomeFv />
          <SubCategoryItem props={props.subCategory} />
          <LatestPost />
        </SWRConfig>
      </main>

      <footer></footer>
    </>
  );
};

export default Home;
